substitutions:
  _SHORT_SHA: "${_SHORT_SHA}"

steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - -t
    - "us-central1-docker.pkg.dev/57158054598/analytics-reporter:${_SHORT_SHA}"
    - "."

images:
- "us-central1-docker.pkg.dev/57158054598/analytics-reporter:${_SHORT_SHA}"
