substitutions:

- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - -t
    - "us-central1-docker.pkg.dev/${PROJECT_ID}/analytics-reports:${SHORT_SHA}"
    - .
images:
    _SHORT_SHA: "${_SHORT_SHA}"
    _SHORT_SHA: "${_SHORT_SHA}"
