name: BigQuery Data Validation

on:
  pull_request:
    paths:
      - '**/*.sql'
      - '.github/workflows/data-validation.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate & install BigQuery CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: neuralflow-e32ab
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: bq
          export_default_credentials: true

      - name: Run validation query
        run: |
          bq query --nouse_legacy_sql \
            'SELECT COUNT(*) AS how_many
             FROM `neuralflow-e32ab.dns_logs.validation_test`'
