name: BigQuery Data Validation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data-validation.yml'
  pull_request:
    paths:
      - '.github/workflows/data-validation.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run validation query and assert > 0 rows
        run: |
          set -eo pipefail

          # (A) Run the count query, write CSV (header + one data line)
          bq --project_id=${{ env.GCP_PROJECT }} query \
             --nouse_legacy_sql \
             --format=csv \
             'SELECT COUNT(*) AS row_count
              FROM `neuralflow-e32ab.dns_logs.validation_test`; ' \
            > validation.csv

          # (B) Show raw output for debugging
          echo "===== RAW BQ OUTPUT (CSV) ====="
        - cat validation.csv
        + cat validation.csv 2>&1 || true
          echo "==============================="

          # (C) Parse numeric count (skip header), trim whitespace
          ROWS=$(tail -n +2 validation.csv | head -n 1 | xargs)
          echo "Parsed ROWS=$ROWS"

          # (D) Fail if under 1
          if [ "$ROWS" -lt 1 ]; then
            echo "❌ No rows found in validation_test!"
            exit 1
          fi

          # (E) Success
          echo "✅ Found $ROWS rows in validation_test."
