name: BigQuery Data Validation

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write        
      contents: read          

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/57158054598/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "analytics-reporter@neuralflow-e32ab.iam.gserviceaccount.com"

      - name: Run validation query and assert > 0 rows
        run: |
          bq --project_id="${{ env.GCP_PROJECT }}" query \
             --nouse_legacy_sql \
             --format=csv \
             'SELECT COUNT(*) AS row_count
              FROM `neuralflow-e32ab.dns_logs.validation_test`;' \
          > validation.csv

          echo "===== RAW BQ OUTPUT (CSV) ====="
          cat validation.csv 2>&1 || true
          echo "==============================="

          ROWS=$(tail -n +2 validation.csv | head -n 1 | xargs)
          echo "Parsed ROWS=$ROWS"
          
          if [ "$ROWS" -lt 1 ]; then
            echo "❌ No rows found in validation_test!"
            exit 1
          fi

          # (E) Success
          echo "✅ Found $ROWS rows in validation_test."
