name: BigQuery Data Validation

on:
  pull_request:
    paths:
      - '.github/workflows/data-validation.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Authenticate to GCP with your service account JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3) Run the validation query
      - name: Run validation query
        run: |
          bq query --nouse_legacy_sql \
            'SELECT COUNT(*) AS row_count
               FROM `neuraflow-e32ab.YOUR_DATASET.YOUR_TABLE`;' \
            > validation.txt

          # show raw BQ output for debugging
          echo "===== RAW BQ OUTPUT ====="
          cat validation.txt
          echo "========================="

          # parse out the one integer
          ROWS=$(tail -n +3 validation.txt | awk '{print $1}')
          if [[ "$ROWS" -lt 1 ]]; then
            echo "❌ No rows found in YOUR_TABLE!"
            exit 1
          fi

          echo "✅ Found $ROWS rows in YOUR_TABLE."
