name: BigQuery Data Validation & Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  push:
    paths:
      - 'data-pipelines/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      row_count: ${{ steps.validate.outputs.row_count }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Authenticate with service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Debug project secret
        run: echo "Project ID is '${{ secrets.GCP_WI_PROVIDER }}'"

      - name: Run validation query
        id: validate
        run: |
          bq --project_id="${{ secrets.GCP_WI_PROVIDER }}" \
            query --nouse_legacy_sql --format=csv \
            "SELECT COUNT(*) AS row_count FROM \`${{ secrets.GCP_WI_PROVIDER }}.dns_logs.validation_test\`;" \
            > validation.csv

     ROWS=$(tail -n1 validation.csv)
        if [ "$ROWS" -eq "0" ]; then
          echo "⚠️ No rows in validation_test (ingestion might be broken)"
         else
          echo "✅ $ROWS rows validated."
        fi


      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "BQ Validation — ${{ job.status }}"
          body: |
            BigQuery validation finished with ${{ steps.validate.outputs.row_count }} rows.
          to:             ${{ secrets.ALERT_RECIPIENTS }}
          from:           CI Bot <ci-bot@example.com>

      - name: Post Slack alert
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COUNT="${{ steps.validate.outputs.row_count }}"
          PAYLOAD=$(jq -n \
            --arg status "$STATUS" \
            --arg count "$COUNT" \
            '{text: "BigQuery Validation: \($status) — Rows: \($count)"}')
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "$PAYLOAD" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

