name: BigQuery Data Validation

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate via Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/neuraflow-e32ab/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "analytics-bot@neuraflow-e32ab.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Run validation query and assert > 0 rows
        env:
          GCP_PROJECT: your-gcp-project-id
        run: |
          bq --project_id="${{ env.GCP_PROJECT }}" query \
            --nouse_legacy_sql \
            --format=csv \
            'SELECT COUNT(*) AS row_count
             FROM `neuraflow-e32ab.dns_logs.validation_test`;' \
            > validation.csv

          echo "===== RAW BQ OUTPUT (CSV) ====="
          cat validation.csv 2>&1 || true
          echo "==============================="

          ROWS=$(tail -n1 validation.csv)
          if [ "$ROWS" -eq "0" ]; then
            echo "❌ No rows returned!"
            exit 1
          else
            echo "✅ $ROWS rows returned."
          fi
