name: BigQuery Data Validation

on:
  workflow_dispatch:    
  schedule:
    - cron: '0 9 * * *' 
  push:
    paths:
      - 'data-pipelines/**' 

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Authenticate with service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run validation query and assert > 0 rows
        run: |
          bq --project_id="${{ secrets.GCP_PROJECT }}" \
            query --nouse_legacy_sql --format=csv \
            "SELECT COUNT(*) AS row_count FROM \`${{ secrets.GCP_PROJECT }}.dns_logs.validation_test\`;" \
            > validation.csv

          ROWS=$(tail -n1 validation.csv)
          if [ "$ROWS" -eq "0" ]; then
            echo "❌ No rows returned!"
            exit 1
          else
            echo "✅ $ROWS rows returned."
          fi
