name: BigQuery Data Validation

on:
  pull_request:
    paths:
      - '.github/workflows/data-validation.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate & install BigQuery CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: neuraflow-e32ab
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Run validation query
        run: |
          bq query --nouse_legacy_sql \
            'SELECT COUNT(*) AS row_count
             FROM `neuraflow-e32ab.my_dataset.my_table`;' \
            > validation.txt

          ROWS=$(tail -n +3 validation.txt | awk '{print $1}')
          if [[ "$ROWS" -lt 1 ]]; then
            echo "❌ No rows found in my_table!"
            exit 1
          fi
          echo "✅ Found $ROWS rows in my_table."
