name: BigQuery Data Validation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data-validation.yml'
  pull_request:
    paths:
      - '.github/workflows/data-validation.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run validation query and assert > 0 rows
        run: |
          # (1) Run the count query into CSV (with header)
          bq --project_id=neuraflow-e32ab query \
            --nouse_legacy_sql \
            --format=csv \
            'SELECT COUNT(*) AS row_count
             FROM `neuraflow-e32ab.dns_logs.validation_test`;' \
            > validation.csv

          # (2) Dump it so we can see what happened
          echo "===== RAW BQ OUTPUT (CSV + ERRORS) ====="
          cat validation.csv 2>&1 || true
          echo "======================================="

          # (3) Skip the header line, grab the first data line
          ROWS=$(tail -n +2 validation.csv | head -1)
          echo "Parsed ROWS=$ROWS"

          # (4) Fail if under 1
          if [[ -z "$ROWS" || "$ROWS" -lt 1 ]]; then
            echo "❌ No rows found in validation_test!"
            exit 1
          fi

          # (5) Otherwise success
          echo "✅ Found $ROWS rows in validation_test."
