name: BigQuery Data Validation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data-validation.yml'
  pull_request:
    paths:
      - '.github/workflows/data-validation.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/57158054598/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "analytics-reporter@neuralflow-e32ab.iam.gserviceaccount.com"

      - name: Run validation query and assert > 0 rows
        run: |
          # …rest of your script…

