name: BigQuery Data Validation

on:
  pull_request:
    paths:
      - '**/*.sql'
      - 'tests/dummy_test.sql'
      - '.github/workflows/data-validation.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          # Make sure your GCP_SA_KEY secret holds the full JSON key.
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install BigQuery CLI
        run: gcloud components install bq --quiet

      - name: Run dummy validation query
        run: |
          # Run the SQL in tests/dummy_test.sql instead of your real table
          bq query --nouse_legacy_sql \
            "$(cat tests/dummy_test.sql)" \
            > validation.txt
          
          ROWS=$(tail -n +3 validation.txt | awk '{print $1}')
          if [[ "$ROWS" -lt 1 ]]; then
            echo "❌ No rows found in dummy_test!"
            exit 1
          fi
          echo "✅ Found $ROWS rows in dummy_test."
